//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncThinkTechnology.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Orders = new HashSet<Order>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int CategoryId { get; set; }
        public int ProductBarcode { get; set; }
        public int TotalOrders { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
