//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncThinkTechnology.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int SupplierId { get; set; }
        public string SupplierBusinessName { get; set; }
        public string SupplierEmail { get; set; }
        public int SupplierPhoneNumber { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
